server:
  port: 8100
spring:
  application:
    name: producer
rocketmq:
  nameServer: 192.168.2.110:9876;192.168.2.120:9876
  producer:
    group: producer_group
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3
    send-message-timeout: 2000
    # 最大消息容量，默认4m
    max-message-size: 4194304


